export const categories = [
  {
    id: 1,
    name: "Pho",
    image: require("../assets/images/pho.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/burger.png"),
  },
  {
    id: 3,
    name: "Pizza",
    image: require("../assets/images/pizza.png"),
  },
  {
    id: 4,
    name: "Thai",
    image: require("../assets/images/thai.png"),
  },
  {
    id: 5,
    name: "Takeout",
    image: require("../assets/images/takeout.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/dessert.png"),
  },
];

export const featured = [
  {
    id: 1,
    title: "Lemongrass? Yum!",
    description: "Lemongrass as the main base for marinade...",
    restaurants: [
      {
        id: 1,
        name: "Pho Auntie",
        image: require("../assets/images/phoauntie-banh.png"),
        description: "Authentic Vietnamese Food",
        lng: -122.0868854,
        lat: 37.694372,
        address: "2690 Castro Valley Blvd",
        stars: 5,
        reviews: "2.8k",
        category: "Vietnamese",
        dishes: [
          {
            id: 1,
            name: "Bún Gà Thịt Nướng",
            description: "Grilled Lemongrass Chicken & Rice Noodle",
            price: 15.25,
            image: require("../assets/images/phoauntie-chicken.png"),
          },
          {
            id: 2,
            name: "Bánh Xèo",
            description: "Crispy & Savory Vietnamese Crêpes / Pancakes",
            price: 15.95,
            image: require("../assets/images/phoauntie-crepe.png"),
          },
          {
            id: 3,
            name: "Bánh Hỏi",
            description:
              "Fine woven noodle sheets, grilled pork, sugarcane shrimp, sausage meatballs, peanut, with fish sauce",
            price: 16.5,
            image: require("../assets/images/phoauntie-mix.png"),
          },
        ],
      },
      {
        id: 2,
        name: "Farmhouse Kitchen Thai Cuisine",
        image: require("../assets/images/farmhousethai-platter.png"),
        description: "Modern take to homecooked Thai food",
        lng: -122.1127021,
        lat: 37.6920466,
        address: "16695 E 14th St",
        stars: 4,
        reviews: "1.4k",
        category: "Thai",
        dishes: [
          {
            id: 1,
            name: "Volcano Noodles",
            description:
              "Spicy noodles stir-fried with our house-made godmother sauce served with a beefy braised rib",
            price: 29.95,
            image: require("../assets/images/farmhousethai-noodles.png"),
          },
          {
            id: 2,
            name: "Lobster Little Lao Set",
            description:
              "Celebrate the 🗽 🇺🇸 4th with 1.5 lb live Maine lobster drizzled with garlic turmeric sauce and our signature dishes",
            price: 94.99,
            image: require("../assets/images/farmhousethai-platter.png"),
          },
          {
            id: 3,
            name: "Thai Iced Tea",
            description:
              "Strong (yet not bitter) tea taste, flavor notes of warm honey & vanilla, creamy consistency, and almost milkshake-like sweetness",
            price: 4.99,
            image: require("../assets/images/farmhousethai-tea.png"),
          },
        ],
      },
      {
        id: 3,
        name: "Sunflower Hayward",
        image: require("../assets/images/sunflower-spread.png"),
        description: "Best Chinese Halal Food",
        lng: -122.0825393,
        lat: 37.6763381,
        address: "1213 A St",
        stars: 4,
        reviews: "1.1k",
        category: "Chinese",
        dishes: [
          {
            id: 1,
            name: "Mongolian Beef",
            description: "One of our most popular dishes!",
            price: 13.99,
            image: require("../assets/images/sunflower-beef.png"),
          },
          {
            id: 2,
            name: "Mushroom Prawns",
            description: "Shrimp with garlic sautéed mushrooms",
            price: 10,
            image: require("../assets/images/sunflower-mushroom.png"),
          },
          {
            id: 3,
            name: "Broccoli Prawns",
            description: "Spicy!",
            price: 10,
            image: require("../assets/images/sunflower-broccoli.png"),
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Sandwich kind of day?",
    description: "If not a Banh Mi? Then a Philly Cheesesteak!",
    restaurants: [
      {
        id: 1,
        name: "Cam Huong",
        image: require("../assets/images/camhuong-combo.png"),
        description: "Vietnamese sandwiches and food to-go",
        lng: -122.6449299,
        lat: 37.5899551,
        address: "32124 Alvarado Blvd",
        stars: 5,
        reviews: "1.9k",
        category: "Vietnamese",
        dishes: [
          {
            id: 1,
            name: "Bánh Mì Ðặc Biệt",
            description: "Special Combination Banh Mi",
            price: 6.5,
            image: require("../assets/images/camhuong-pork.png"),
          },
          {
            id: 2,
            name: "Bánh Mì Thịt Nướng",
            description:
              "Barbecued meat, pickled carrots /daikon, on a fresh baguette",
            price: 6.25,
            image: require("../assets/images/camhuong-beef.png"),
          },
          {
            id: 3,
            name: "Bánh Cuốn",
            description: "Freshly steamed rice wrappers with pork and veggies",
            price: 7.99,
            image: require("../assets/images/camhuong-banh.png"),
          },
        ],
      },
      {
        id: 2,
        name: "Bob's Hoagy Steaks",
        image: require("../assets/images/bogshoagy-combo.png"),
        description: "BBQ fresh everyday!",
        lng: -122.0508874,
        lat: 37.6294537,
        address: "29623 Mission Blvd",
        stars: 4,
        reviews: "1.3k",
        category: "Sandwich",
        dishes: [
          {
            id: 1,
            name: "Short Rib Combo Plate",
            description: "Hickory smoked short ribs with choice of 2 sides",
            price: 14.5,
            image: require("../assets/images/bogshoagy-shortrib.png"),
          },
          {
            id: 2,
            name: "Seafood Combo Plate",
            description: "Fried fish with choice of 2 sides",
            price: 16.5,
            image: require("../assets/images/bogshoagy-seafood.png"),
          },
          {
            id: 3,
            name: "BBQ Steak Sandwich",
            description:
              "Slow cooked steak sandwich with choice of our 15 bbq sauces",
            price: 13.5,
            image: require("../assets/images/bogshoagy-bbq.png"),
          },
        ],
      },
      {
        id: 3,
        name: "Dave's Hot Chicken",
        image: require("../assets/images/bogshoagy-combo.png"),
        description: "BBQ fresh everyday!",
        lng: -122.356925,
        lat: 37.5992722,
        address: "32200 Dyer St",
        stars: 5,
        reviews: "3.6k",
        category: "Sandwich",
        dishes: [
          {
            id: 1,
            name: "Spicy Chicken Sandwich",
            description: "Pick between level 1 and 10!",
            price: 12.5,
            image: require("../assets/images/daveschicken-spicy.png"),
          },
          {
            id: 2,
            name: "Coleslaw",
            description: "No raisins, we promise!",
            price: 3.99,
            image: require("../assets/images/daveschicken-coleslaw.png"),
          },
          {
            id: 3,
            name: "Oreo Shake",
            description: "Come to our restaurant and we can spike it!",
            price: 5.5,
            image: require("../assets/images/daveschicken-oreo.png"),
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Always room for dessert",
    description: "Cupcakes, candies, brownies, galore",
    restaurants: [
      {
        id: 1,
        name: "Marley's Treats",
        image: require("../assets/images/marleystreats-truck.png"),
        description: "Filipino inspired desserts",
        lng: -123.2382774,
        lat: 37.6718644,
        address: "838 B St, Hayward",
        stars: 5,
        reviews: "3.8k",
        category: "Desserts",
        dishes: [
          {
            id: 1,
            name: "Ice Cream",
            description: "Choose flavor, each extra scoop is $3!",
            price: 4,
            image: require("../assets/images/marleystreats-icecream.png"),
          },
          {
            id: 2,
            name: "Ube Flan",
            description: "Fresh flan with Ube base",
            price: 4.99,
            image: require("../assets/images/marleystreats-flan.png"),
          },
          {
            id: 3,
            name: "Ube Crinkle Cookie",
            description: "Filled with custard!",
            price: 16.5,
            image: require("../assets/images/marleystreats-cookie.png"),
          },
        ],
      },
      {
        id: 2,
        name: "Milk & Cookie Bar",
        image: require("../assets/images/milkcookie-order.png"),
        description: "Everything is made in house, including our sweet bread!",
        lng: -122.0938589,
        lat: 37.708624,
        address: "18911 Lake Chabot Rd",
        stars: 5,
        reviews: "2.3k",
        category: "Desserts",
        dishes: [
          {
            id: 1,
            name: "Ice Cream Shake",
            description: "Customize your shake",
            price: 7.5,
            image: require("../assets/images/milkcookie-shake.png"),
          },
          {
            id: 2,
            name: "Ice Crean Scoop",
            description: "Choose from over 40 flavors",
            price: 4,
            image: require("../assets/images/milkcookie-scoop.png"),
          },
          {
            id: 3,
            name: "Ice Cream Sandwich",
            description:
              "Pick your favorite flavor in warm homemade sweet bread",
            price: 6,
            image: require("../assets/images/milkcookie-sandwich.png"),
          },
        ],
      },
      {
        id: 3,
        name: "Taste of Mochi",
        image: require("../assets/images/tasteofmochi-platter.png"),
        description: "Ingredients imported straight from Japan!",
        lng: -122.0693121,
        lat: 37.6443983,
        address: "-",
        stars: 5,
        reviews: "2.3k",
        category: "Desserts",
        dishes: [
          {
            id: 1,
            name: "Matcha Mochi",
            description: "Glutinous sweet rice flour and green tea powder",
            price: 3,
            image: require("../assets/images/tasteofmochi-matcha.png"),
          },
          {
            id: 2,
            name: "Red Bean Matcha",
            description: "Sweeted with Monk Fruit Sugar!",
            price: 3,
            image: require("../assets/images/tasteofmochi-redbean.png"),
          },
          {
            id: 3,
            name: "Rose Mochi",
            description: "Syrup made in house from rose petals!",
            price: 3,
            image: require("../assets/images/tasteofmochi-rose.png"),
          },
        ],
      },
    ],
  },
];
